namespace ThemeStudio.Helper;

public class FontHelper
{
    public static string[] FontNames = {
        "Adobe Devanagari", "Agency FB", "Algerian", "Arial", "Arial Black", "Arial Narrow", "Arial Rounded MT Bold",
        "Bahnschrift", "Bahnschrift Condensed", "Bahnschrift Light", "Bahnschrift Light Condensed",
        "Bahnschrift Light SemiCondensed", "Bahnschrift SemiBold", "Bahnschrift SemiBold Condensed",
        "Bahnschrift SemiBold SemiConden", "Bahnschrift SemiCondensed", "Bahnschrift SemiLight",
        "Bahnschrift SemiLight Condensed", "Bahnschrift SemiLight SemiConde", "Baskerville Old Face", "Bauhaus 93",
        "Bell MT", "Berlin Sans FB", "Berlin Sans FB Demi", "Bernard MT Condensed", "Blackadder ITC", "Bodoni MT",
        "Bodoni MT Black", "Bodoni MT Condensed", "Bodoni MT Poster Compressed", "Book Antiqua", "Bookman Old Style",
        "Bookshelf Symbol 7", "Bradley Hand ITC", "Britannic Bold", "Broadway", "Brush Script MT", "Calibri",
        "Calibri Light", "Californian FB", "Calisto MT", "Cambria", "Cambria Math", "Candara", "Candara Light",
        "Cascadia Code", "Cascadia Code ExtraLight", "Cascadia Code Light", "Cascadia Code SemiBold",
        "Cascadia Code SemiLight", "Cascadia Mono", "Cascadia Mono ExtraLight", "Cascadia Mono Light",
        "Cascadia Mono SemiBold", "Cascadia Mono SemiLight", "CaskaydiaCove Nerd Font", "CaskaydiaCove Nerd Font Mono",
        "CaskaydiaCove NF", "Castellar", "Centaur", "Century", "Century Gothic", "Century Schoolbook", "Chiller",
        "Colonna MT", "Comic Sans MS", "Consolas", "Constantia", "Cooper Black", "Copperplate Gothic Bold",
        "Copperplate Gothic Light", "Corbel", "Corbel Light", "Courier New", "Curlz MT", "Dubai", "Dubai Light",
        "Dubai Medium", "Ebrima", "Edwardian Script ITC", "Elephant", "Engravers MT", "Eras Bold ITC", "Eras Demi ITC",
        "Eras Light ITC", "Eras Medium ITC", "Felix Titling", "Footlight MT Light", "Forte", "Franklin Gothic Book",
        "Franklin Gothic Demi", "Franklin Gothic Demi Cond", "Franklin Gothic Heavy", "Franklin Gothic Medium",
        "Franklin Gothic Medium Cond", "Freestyle Script", "French Script MT", "Gabriola", "Gadugi", "Garamond",
        "Georgia", "Gigi", "Gill Sans MT", "Gill Sans MT Condensed", "Gill Sans MT Ext Condensed Bold",
        "Gill Sans Ultra Bold", "Gill Sans Ultra Bold Condensed", "Gloucester MT Extra Condensed", "Goudy Old Style",
        "Goudy Stout", "Haettenschweiler", "Harlow Solid Italic", "Harrington", "High Tower Text",
        "HoloLens MDL2 Assets", "Impact", "Imprint MT Shadow", "Informal Roman", "Ink Free", "Javanese Text",
        "Jokerman", "Juice ITC", "Kristen ITC", "Kunstler Script", "Lato", "Lato Light", "Lato Semibold",
        "Leelawadee UI", "Leelawadee UI Semilight", "Lucida Bright", "Lucida Calligraphy", "Lucida Console",
        "Lucida Fax", "Lucida Handwriting", "Lucida Sans", "Lucida Sans Typewriter", "Lucida Sans Unicode", "Magneto",
        "Maiandra GD", "Malgun Gothic", "Malgun Gothic Semilight", "Marlett", "Matura MT Script Capitals",
        "Microsoft Himalaya", "Microsoft JhengHei", "Microsoft JhengHei Light", "Microsoft JhengHei UI",
        "Microsoft JhengHei UI Light", "Microsoft New Tai Lue", "Microsoft PhagsPa", "Microsoft Sans Serif",
        "Microsoft Tai Le", "Microsoft YaHei", "Microsoft YaHei Light", "Microsoft YaHei UI",
        "Microsoft YaHei UI Light", "Microsoft Yi Baiti", "MingLiU-ExtB", "MingLiU_HKSCS-ExtB", "Mistral",
        "Modern No. 20", "Mongolian Baiti", "Monotype Corsiva", "MS Gothic", "MS Outlook", "MS PGothic",
        "MS Reference Sans Serif", "MS Reference Specialty", "MS UI Gothic", "MT Extra", "MV Boli", "Myanmar Text",
        "Niagara Engraved", "Niagara Solid", "Nirmala UI", "Nirmala UI Semilight", "NSimSun", "OCR A Extended",
        "Old English Text MT", "Onyx", "Palace Script MT", "Palatino Linotype", "Papyrus", "Parchment", "Perpetua",
        "Perpetua Titling MT", "Playbill", "PMingLiU-ExtB", "Poor Richard", "Pristina", "Rage Italic", "Ravie",
        "Rockwell", "Rockwell Condensed", "Rockwell Extra Bold", "ROG Fonts", "Sans Serif Collection", "Script MT Bold",
        "Segoe Fluent Icons", "Segoe MDL2 Assets", "Segoe Print", "Segoe Script", "Segoe UI", "Segoe UI Black",
        "Segoe UI Emoji", "Segoe UI Historic", "Segoe UI Light", "Segoe UI Semibold", "Segoe UI Semilight",
        "Segoe UI Symbol", "Segoe UI Variable Display", "Segoe UI Variable Display Light",
        "Segoe UI Variable Display Semib", "Segoe UI Variable Display Semil", "Segoe UI Variable Small",
        "Segoe UI Variable Small Light", "Segoe UI Variable Small Semibol", "Segoe UI Variable Small Semilig",
        "Segoe UI Variable Text", "Segoe UI Variable Text Light", "Segoe UI Variable Text Semibold",
        "Segoe UI Variable Text Semiligh", "Showcard Gothic", "SimSun", "SimSun-ExtB", "Sitka Banner",
        "Sitka Banner Semibold", "Sitka Display", "Sitka Display Semibold", "Sitka Heading", "Sitka Heading Semibold",
        "Sitka Small", "Sitka Small Semibold", "Sitka Subheading", "Sitka Subheading Semibold", "Sitka Text",
        "Sitka Text Semibold", "Snap ITC", "Source Code Pro", "Source Code Pro Black", "Source Code Pro ExtraLight",
        "Source Code Pro Light", "Source Code Pro Semibold", "Stencil", "Sylfaen", "Symbol", "Tahoma", "TeamViewer15",
        "Tempus Sans ITC", "Times New Roman", "Trebuchet MS", "Tw Cen MT", "Tw Cen MT Condensed",
        "Tw Cen MT Condensed Extra Bold", "Verdana", "Viner Hand ITC", "Vivaldi", "Vladimir Script", "Webdings",
        "Wide Latin", "Wingdings", "Wingdings 2", "Wingdings 3", "Yu Gothic", "Yu Gothic Light", "Yu Gothic Medium",
        "Yu Gothic UI", "Yu Gothic UI Light", "Yu Gothic UI Semibold", "Yu Gothic UI Semilight", "ZWAdobeF"
    };
}